[package]
name = "lessons"
version = "0.1.0"
edition = "2021"

[lib]
name = "activity"
path = "src/dir/activitylib.rs"

[dependencies]
thiserror = "2"
crossbeam-channel = "*"
colored = "*"
parking_lot = "0.12.3"
